// <auto-generated />
namespace DocDesckApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class backAllowEmpty_Comment_and_File : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(backAllowEmpty_Comment_and_File));
        
        string IMigrationMetadata.Id
        {
            get { return "201702151306145_backAllowEmpty_Comment_and_File"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
